#!/usr/bin/env bash

normalize-path() {
    local path=/$1

    IFS='/' read -r -a parts <<< "$path"

    local part
    local -a out=()
    for part in "${parts[@]}"; do
        case $part in
        '') ;; # ignore empty dir (multiple /)
        '.') ;; # ignore current dir
        '..') unset 'out[-1]' 2>/dev/null;;
        *) out+=("$part");;
        esac
    done

    local string
    string=$(IFS=/; echo "${out[*]}")
    echo "/$string"
}


normalize-path '../../../../../../../etc/passwd'
# /etc/passwd'
normalize-path '/./.././.././././././tmp/././././'
# '/tmp'
normalize-path '/usr/bin/../lib//./'
# '/usr/lib'

